#!/usr/bin/python
# -*- coding:utf8 -
from PIL import Image

x = 280  # x坐标  通过对txt里的行数进行整数分解
y = 280  # y坐标  

im = Image.new("RGB", (x, y))
file = open('href.txt')

for i in range(0, x):
    for j in range(0, y):
        line = file.readline().replace('(', '').replace(')', '')  # 获取一行rgb值，并且把()都替换为空
        rgb = line.split(",")  # 逗号分割
        im.putpixel((i, j), (int(rgb[0]), int(rgb[1]), int(rgb[2])))  # （i,j）为坐标，后面的是像素点

im.save("flag.png")
